### PR TITLE
Update cowboy dependency to 1.0.3

### PR DESCRIPTION
**Pull request by nacmartin**
The dependency cowboy 1.0.1 throws an error during `make`:

```
cd /private/tmp/bullet/deps/cowboy ; git checkout -q 1.0.1
Unknown or invalid dependency: cowlib. Please consult the erlang.mk README for instructions.
make[1]: *** [/private/tmp/bullet/deps/cowlib] Error 78
```

### CODE REVIEW

**Comment by nacmartin** [comment]
I saw that updating erlang.mk fixed this as well. I have added a commit updating it. Now, it could compile with cowboy 1.0.1 as well with the new erlang.mk, but I guess bumping the dependency to 1.0.3 won't hurt. I guess you know better what can be going on :)

**Comment by essen** [comment]
Looks fine, thanks. Should be merged later today.

**Comment by joaohf** [comment]
Hi, @essen. Could you merge this?

**Comment by essen** [comment]
Thanks and sorry I didn't take care of it, I'm closing this now since we're in the Cowboy 2 era.

**Pull request closed without merging**
