### PR TITLE
match against ok and close instead of crashing on close

### PR DESCRIPTION
**Pull request by marianoguerra**

### CODE REVIEW

**Comment by marianoguerra** [comment]
PR for issue #77

**Comment by marianoguerra** [comment]
just added another match which I could see in the logs after the ones from the previous commit weren't there anymore, it seems to happen less frequently.

**Comment by essen** [comment]
Cheers; I need to move this repository to ninenines, I'm not seeing it when I do work on tickets. Feel free to remind me if I don't before this week-end. :-)

**Comment by marianoguerra** [comment]
bump! :)

**Comment by essen** [comment]
OK I will try to work on it this week-end, remind me at that time please. Right now it's not possible.

**Comment by marianoguerra** [comment]
bump (don't worry if you are busy, just reminding you as requested :)

**Comment by mokevnin** [comment]
Bump), we have the same issue.

**Comment by marianoguerra** [comment]
just to add a note, this has been running in production for me since august without a problem.

**Pull request merged**
