### PR TITLE
silence utf error

### PR DESCRIPTION
**Pull request by barberj**
Fixes

screen shot 2016-01-16 at 7 11 01 am

The retry is not successful.

### CODE REVIEW

**Comment by barberj** [comment]
@essen - Seems this is an issue that keeps being brought up. How do you feel about this for a resolution?

**Comment by essen** [comment]
I don't have this problem. Are you using an old Erlang or something?

**Comment by barberj** [comment]
Thanks for the response. I was under the impression i was at the latest as the auto installer reminds me of updates. I've gone about uninstalling and reinstalling but the download page seems to be bunk at the moment. I know i had installed once using brew as well so I've made sure that is gone so I'm not inadvertently hitting that instance.

I'll reach back out when I'm certain I'm on 18.2 if its still an issue.

Thanks

**Comment by essen** [comment]
Also see 730386451db3afff09b912cf5f7bfdcf3d2435cf.

**Comment by barberj** [comment]
Completely removed erlang. Reinstalled and still getting the issues... I have attached a screen shot showing my version as well. I installed 18.2.1 so not sure why it says 18.0.


screen shot 2016-01-18 at 9 24 00 pm


Thoughts?

**Comment by barberj** [comment]
initially put wrong screen shot... i updated previous comment

**Comment by essen** [comment]
Are you sure you have the most recent bullet version? And by that I don't mean the latest tag, but the latest commit.

**Comment by barberj** [comment]
I removed and refetched.

screen shot 2016-01-19 at 6 49 08 am

**Comment by barberj** [comment]
I've also noted that the solution i have proposed in this PR doesn't work. I must have not removed the beam I compiled when I changed the breaking line.

**Comment by barberj** [comment]
hrm... that tag doesn't correlate to master. perhaps i need to blow away the rebar.lock file. Sorry for the added noise as i learn.

**Comment by barberj** [comment]
:tada: 

screen shot 2016-01-19 at 7 02 25 am

Thanks for lending the ear. New to erlang and rebar3. So ultimately the issue was i was retrieving the latest tag and not master head for bullet. Once i updated the rebar config and blew away the lock file and re-fetched everything works.

**Comment by essen** [comment]
I have no idea about rebar3. I built and use Erlang.mk. Good to know everything works! Thanks.

**Pull request closed without merging**
