### PR TITLE
Update cowboy dependency to 1.0.4

### PR DESCRIPTION
**Pull request by joaohf**
Just an update.

### CODE REVIEW

**Comment by essen** [comment]
Can't merge this, the git url should be using https. If you can also make it https in rebar.config that'd be great, looks like it was forgotten.

**Comment by joaohf** [comment]
Hi @essen. Now using https.

**Comment by essen** [comment]
Can you also fix extend->ninenines in the Makefile while at it? :-)

**Comment by joaohf** [comment]
Done.

**Comment by essen** [comment]
Merged, thanks!

**Pull request merged**
